### ISSUE TITLE
Event Details: UI elements overlap at certain browser widths

### ISSUE THREAD

**Issue by erinchambers** [unl/UNL_Events#151]
On the page for adding or editing a calendar event, the far right column (+New Event, Tools, Your Calendars, etc.) overlaps the middle column (Sharing, Contact Info, Image) at certain browser widths. 

I'm seeing it happen in Firefox at browser widths of 880px to 1360px or so. Easily circumvented by changing the width of the browser window, but wanted to make sure it's on your radar.
 
![Screen Shot 2021-06-22 at 11 29 28 AM](https://user-images.githubusercontent.com/12901264/122964921-5fe94e00-d34d-11eb-82ab-45cd3dfffff6.png)

**Comment by jsturek** [comment]
I updated the cache bust variable so new CSS should be used instead of old cached version.

**Comment by erinchambers** [comment]
Hey @jsturek—still having the problem.

**Comment by jsturek** [comment]
@erinchambers, I'm not seeing the issue on firefox (or other browsers).  Try a hard refresh or clear cache.

**Comment by jsturek** [comment]
@erinchambers. I was able to replicate only with events with long titles on edit.  I will handle that by truncating the title in the breadcrumb.
