### ISSUE TITLE
Two room fields could be confusing

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_Events#33]
There are two room fields, one on the new location form and one on the new event form.  I bet the two fields could be confusing, especially if a location has a room already defined.

I think the event room field is there for locations which are just buildings (and no specific room defined), so that a location of say 420 University Terrace could be chosen, and then you can select which room you want.

There is still value in defining a room on a location if the location is that specific.  

So, my idea is this: if the location room is defined, disable the event room field and show the locations room value.

Thoughts?

**Comment by jsturek** [comment]
old issue
