### ISSUE TITLE
Subscriptions might not be working correctly

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_Events#36]
I have gotten reports that subscriptions are not working, or working erratically.

I searched the code base for `processSubscriptions()` and `process()` and found that subscriptions are only being processed when they are edited or inserted.  @tlemburg can you confirm?  Am I missing something?

`Calendar::processSubscriptions()` doesn't appear to be used at all?

**Comment by mfairchild365** [comment]
ah, it looks like subscriptions are being handled here: https://github.com/unl/UNL_UCBCN_System/blob/master/src/UNL/UCBCN/Calendar.php#L186-L197

It looks like this should be fine.  I'm going to ask the person with this issue to delete their subscription and recreate it, but that depends on this being deployed: https://github.com/unl/UNL_UCBCN_System/pull/35

**Comment by tlemburg** [comment]
Cool. I will deploy that and the other issue shortly.

**Comment by mfairchild365** [comment]
Sweet, thanks!

**Comment by mfairchild365** [comment]
Ah, so this was the issue:

```
The events that are designated as public seem to be importing correctly. I accidentally left 2 events as private, and they did not import. When I changed them to public, the subscription didn’t pick-up on the change and they are still not importing…
```

So it looks like we should do the subscription logic on save rather than just on insert.  What do you think @tlemburg ?

**Comment by jsturek** [comment]
Old or resolved issue
