### ISSUE TITLE
Add option to select all events in tab

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_Events#40]
Question:

```
Is there any way to delete all of the past events on the Past tab all at once?
Or do I have to delete them one page at a time?
```

For folks who have hundreds of pages, it might be helpful to add the option to 'select all events under this tab'.

**Comment by tlemburg** [comment]
Hey Michael, lets get these reported in Trello at https://trello.com/b/chBWCLZe/unl-events . I'm better at issue tracking there and that's where all these "want-to-haves" are getting put right now.

**Comment by mfairchild365** [comment]
Sounds good

**Comment by jsturek** [comment]
Addressed with calendar's `Event Clean Up` page
